"""Tool endpoints for CV Pro — AI-powered CV section rewriting.

Each tool takes structured CV data + JD data, sends them through the
prompt engine to Claude, parses the response, and returns structured JSON.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from services.claude_client import call_claude
from services.prompt_engine import load_prompt
from services.response_parser import parse_projects_response


# --- Pydantic models ---


class ToolRequest(BaseModel):
    """Shared request body for all tool endpoints.

    Attributes:
        cv_data: Structured CV data from the frontend input boxes.
        jd_data: Job description data with raw_text and keywords.
    """

    cv_data: dict
    jd_data: dict


class BulletVariation(BaseModel):
    """A single angle variation of a bullet.

    Attributes:
        angle: The variation angle — "tech", "impact", or "problem".
        text: The rewritten bullet text.
    """

    angle: str
    text: str


class BulletResult(BaseModel):
    """Original bullet paired with its AI-generated variations.

    Attributes:
        original: The original bullet text from the user's CV.
        variations: List of angle variations generated by Claude.
    """

    original: str
    variations: list[BulletVariation]


class ProjectResult(BaseModel):
    """A single project with its rewritten bullets.

    Attributes:
        title: Project title (e.g. "ThinkRoom | Full Stack").
        bullets: List of original bullets with their variations.
    """

    title: str
    bullets: list[BulletResult]


class ProjectsResponse(BaseModel):
    """Response from the projects rewriting tool.

    Attributes:
        projects: Dict mapping project keys to their rewritten results.
        suggestions: Optional improvement suggestions from Claude.
    """

    projects: dict[str, ProjectResult]
    suggestions: list[str] = []


# --- Router ---

router = APIRouter(prefix="/api/tools", tags=["tools"])


@router.post("/projects", response_model=ProjectsResponse)
async def rewrite_projects(request: ToolRequest) -> ProjectsResponse:
    """Rewrite project bullets with angle variations (Tool 1).

    Loads the projects.md prompt, sends CV projects + JD to Claude,
    and returns per-bullet variations with tech/impact angles.

    Args:
        request: ToolRequest with cv_data containing projects and jd_data.

    Returns:
        ProjectsResponse with rewritten bullets and suggestions.

    Raises:
        HTTPException: On prompt loading errors (404) or parse errors (422).
    """
    try:
        system_prompt, user_message = await load_prompt(
            "projects", request.cv_data, request.jd_data
        )
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))

    # Call Claude — errors are raised as HTTPException by claude_client
    raw_response = await call_claude(system_prompt, user_message)

    # Parse Claude's markdown output into structured JSON
    try:
        parsed = parse_projects_response(
            raw_response, request.cv_data.get("projects", {})
        )
    except ValueError as e:
        raise HTTPException(
            status_code=422,
            detail=f"Failed to parse Claude response: {e}",
        )

    return ProjectsResponse(**parsed)
